export const SIGNUP_INITIALIZED = 'SIGNUP_REQUESTED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const LOGIN_INITIALIZED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_INITIALIZED = 'LOGOUT_INITIALIZED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const FETCH_MEETUPS_INITIALIZED = 'FETCH_MEETUPS_INITIALIZED';
export const FETCH_MEETUPS_SUCCESS = 'FETCH_MEETUPS_SUCCESS';
export const FETCH_MEETUPS_ERROR = 'FETCH_MEETUPS_ERROR';

export const CREATE_MEETUPS_INITIALIZED = 'CREATE_MEETUPS_INITIALIZED';
export const CREATE_MEETUPS_SUCCESS = 'CREATE_MEETUPS_SUCCESS';
export const CREATE_MEETUPS_ERROR = 'CREATE_MEETUPS_ERROR';

export const FETCH_SINGLE_MEETUPS_INITIALIZED =
  'FETCH_SINGLE_MEETUPS_INITIALIZED';
export const FETCH_SINGLE_MEETUPS_SUCCESS = 'FETCH_SINGLE_MEETUPS_SUCCESS';
export const FETCH_SINGLE_MEETUPS_ERROR = 'FETCH_SINGLE_MEETUPS_ERROR';

export const FETCH_QUESTION_INITIALIZED = 'FETCH_QUESTION_INITIALIZED';
export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS';
export const FETCH_QUESTION_ERROR = 'FETCH_QUESTION_ERROR';
